#!/usr/bin/env python3
"""Sync Spanish translations from the English source files.

English is the source of truth. The Spanish files (data/es/*.yaml,
i18n/es.yaml, content/**/*.es.md) are GENERATED by this script from their
English counterparts - do not hand-edit them, your edits will be overwritten
the next time the matching English file changes.

Not covered (edit by hand, they rarely change): the Spanish menu names in
hugo.toml, and content/portal.md (deliberately English-only).

Usage:
  python3 scripts/translate_es.py            # translate files whose English changed
  python3 scripts/translate_es.py --dry-run  # list what would be translated
  python3 scripts/translate_es.py --all      # force retranslate everything
  python3 scripts/translate_es.py --seed     # mark current Spanish as up to date

Auth: ANTHROPIC_API_KEY env var, or an `ant auth login` profile.
State: scripts/.translation-state.json maps each English file to the hash it
had when its Spanish counterpart was last generated.
"""

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STATE_FILE = Path(__file__).resolve().parent / ".translation-state.json"

MODEL = "claude-opus-4-8"

SYSTEM_PROMPT = """\
You translate website copy for BYLD (gobyld.com), a Madrid-based modular \
construction company, from English to Spanish (Spain). You receive one \
complete source file and return the complete translated file.

Rules:
- Return ONLY the translated file content. No code fences, no commentary.
- Preserve the file's exact structure: YAML keys, front matter fields, \
markdown formatting, list structure, and comments. Translate only \
human-readable values.
- Never change: file paths, image paths, URLs, slugs, weight values, logo \
references, email addresses, layout/passwordHash/build fields, HTML.
- Internal site links: "/#section" becomes "/es/#section". Relative links \
like "solar-study/" stay unchanged. External URLs stay unchanged.
- Brand and product names stay as-is: BYLD, ECHO, The ICON, ATLAS, \
Hub Culture, Arup, Climetric, TVA, Hedera, CLT.
- Award names stay in English (e.g. "Designer of the Year 2025", \
"A+Awards 2026", "Pop-Ups & Temporary"); translate "Winner" as "Ganador".
- Status values: "Available" -> "Disponible"; "In development" or \
"In Development" -> "En desarrollo".
- Press quotes (any `quote` field) stay verbatim in their original \
language, whatever it is. In press files translate only `accolade` values.
- Comparison values follow the pattern "Keyword – description". Keep the \
" – " separator (space, en dash, space) exactly as in the source; the \
site's code splits on it.
- Sector labels: Hospitality -> Hotelero, Commercial -> Comercial, \
Residential -> Residencial.
- Style: natural Spanish of Spain for an architecture brand. Confident, \
plain, direct. No em dashes in prose. No marketing filler, no AI-sounding \
phrasing. Use tú where the English addresses the reader as "you".
- The output must stay machine-readable: valid YAML (quote any value \
containing a colon) and, for markdown files, intact `---` front matter \
delimiters.\
"""


def source_pairs():
    """(english_source, spanish_target) for every file we keep in sync."""
    pairs = []
    for src in sorted((ROOT / "data" / "en").glob("*.yaml")):
        if src.name == "projects.yaml":  # unused on the site
            continue
        pairs.append((src, ROOT / "data" / "es" / src.name))
    pairs.append((ROOT / "i18n" / "en.yaml", ROOT / "i18n" / "es.yaml"))
    for src in sorted((ROOT / "content").rglob("*.md")):
        if src.name.endswith(".es.md") or src.name == "portal.md":
            continue
        pairs.append((src, src.with_name(src.name[:-3] + ".es.md")))
    return pairs


def file_hash(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load_state():
    if STATE_FILE.exists():
        return json.loads(STATE_FILE.read_text())
    return {}


def save_state(state):
    STATE_FILE.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n")


def rel(path):
    return path.relative_to(ROOT).as_posix()


def validate(target, text):
    """Raise if the translated output is not machine-readable."""
    import yaml

    if target.suffix == ".yaml":
        yaml.safe_load(text)
    else:
        if not text.startswith("---"):
            raise ValueError("missing front matter opening delimiter")
        parts = text.split("---", 2)
        if len(parts) < 3:
            raise ValueError("missing front matter closing delimiter")
        yaml.safe_load(parts[1])


def strip_fences(text):
    text = text.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[1]
        if text.rstrip().endswith("```"):
            text = text.rstrip()[: -len("```")]
    return text.strip() + "\n"


def translate_file(client, src, target):
    content = src.read_text()
    response = client.messages.create(
        model=MODEL,
        max_tokens=16000,
        thinking={"type": "adaptive"},
        system=SYSTEM_PROMPT,
        messages=[
            {
                "role": "user",
                "content": (
                    f"Source file: {rel(src)}\n"
                    f"Target file: {rel(target)}\n\n"
                    f"{content}"
                ),
            }
        ],
    )
    text = "".join(b.text for b in response.content if b.type == "text")
    return strip_fences(text)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--all", action="store_true")
    parser.add_argument("--seed", action="store_true")
    args = parser.parse_args()

    state = load_state()
    pairs = source_pairs()

    if args.seed:
        save_state({rel(src): file_hash(src) for src, _ in pairs})
        print(f"Seeded {STATE_FILE.name} with {len(pairs)} entries.")
        return

    stale = []
    for src, target in pairs:
        current = file_hash(src)
        if args.all or not target.exists() or state.get(rel(src)) != current:
            stale.append((src, target, current))

    if not stale:
        print("Spanish translations are up to date.")
        return

    if args.dry_run:
        for src, target, _ in stale:
            print(f"would translate: {rel(src)} -> {rel(target)}")
        return

    import anthropic

    client = anthropic.Anthropic()
    failures = 0
    for src, target, current in stale:
        print(f"translating: {rel(src)} -> {rel(target)}")
        try:
            for attempt in (1, 2):
                text = translate_file(client, src, target)
                try:
                    validate(target, text)
                    break
                except Exception as err:
                    if attempt == 2:
                        raise
                    print(f"  invalid output ({err}); retrying once")
        except anthropic.AuthenticationError:
            sys.exit("error: Claude API authentication failed - check ANTHROPIC_API_KEY")
        except Exception as err:
            print(f"  FAILED ({err}); keeping the existing Spanish file")
            failures += 1
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text)
        state[rel(src)] = current
        save_state(state)

    print(f"Done: {len(stale) - failures} translated, {failures} failed.")


if __name__ == "__main__":
    main()
